name: Prepare pull request for release

run-name: Prepare ONLYOFFICE_DesktopEditors-${{ github.event.inputs.version }} to release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
      with:
        ref: release/v${{ github.event.inputs.version }}

    - name: Replace Version and Build Number
      id: repl
      run: |
        VERSION=${{ github.event.inputs.version }}
        #replace version
        #sed -i -r "/url/s/([0-9]+).([0-9]+).([0-9]+)/${VERSION}/" ./org.onlyoffice.desktopeditors.json
        #remove build number
        sed -i -r "/url/s/-([0-9]+)-/-/" ./org.onlyoffice.desktopeditors.json
        #replace link to archive to test
        sed -i -e '/url/s|https://s3.eu-west-1.amazonaws.com/repo-doc-onlyoffice-com|http://download.onlyoffice.com/install|' ./org.onlyoffice.desktopeditors.json
        sed -i -e '/url/s|linux/generic|editors/linux|' ./org.onlyoffice.desktopeditors.json
        sed -i -e "/url/s|-x86_64|-x64|" ./org.onlyoffice.desktopeditors.json
        #commit changes
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Prepare to release" -a
        git push

